import type { WorkspaceState } from '../types';
import { AGENT_MAP } from '../data/mockAgents';

/**
 * Generates a formatted Markdown export of the full workspace output.
 */
export function generateMarkdownExport(state: WorkspaceState): string {
  const now = new Date();
  const dateStr = now.toLocaleDateString('en-US', {
    year: 'numeric', month: 'long', day: 'numeric',
  });
  const timeStr = now.toLocaleTimeString('en-US', {
    hour: '2-digit', minute: '2-digit',
  });

  const lines: string[] = [];

  // Header
  lines.push('# Orbit Workspace Export');
  lines.push('');
  lines.push(`**Exported:** ${dateStr} at ${timeStr}`);
  lines.push('');
  lines.push('---');
  lines.push('');

  // Goal
  lines.push('## Goal');
  lines.push('');
  lines.push(`> ${state.goal}`);
  lines.push('');
  if (state.context) {
    lines.push('**Context:**');
    lines.push(state.context);
    lines.push('');
  }
  lines.push('---');
  lines.push('');

  // Agent workstreams
  const agentOrder = ['strategist', 'researcher', 'builder'] as const;

  for (const agentId of agentOrder) {
    const workstream = state.workstreams[agentId];
    if (!workstream) continue;

    const agent = AGENT_MAP[agentId];
    lines.push(`## ${agent.name} — ${agent.specialty}`);
    lines.push('');

    for (const section of workstream.sections) {
      lines.push(`### ${section.title}`);
      lines.push('');
      lines.push(section.content);
      lines.push('');

      if (section.citations && section.citations.length > 0) {
        lines.push('**Sources:**');
        for (const c of section.citations) {
          lines.push(`- ${c.label}: ${c.source}`);
        }
        lines.push('');
      }
    }

    lines.push('---');
    lines.push('');
  }

  // Key Decisions
  if (state.insights.decisions.length > 0) {
    lines.push('## Key Decisions');
    lines.push('');
    for (const d of state.insights.decisions) {
      const agent = AGENT_MAP[d.agent];
      lines.push(`### ${d.title}`);
      lines.push(`*Priority: ${d.priority} · Recommended by: ${agent.name}*`);
      lines.push('');
      lines.push(d.description);
      lines.push('');
    }
    lines.push('---');
    lines.push('');
  }

  // Risks
  if (state.insights.risks.length > 0) {
    lines.push('## Risks');
    lines.push('');
    for (const r of state.insights.risks) {
      lines.push(`### ⚠️ ${r.title}`);
      lines.push(`*Severity: ${r.severity}*`);
      lines.push('');
      lines.push(r.description);
      lines.push('');
      lines.push(`**Mitigation:** ${r.mitigation}`);
      lines.push('');
    }
    lines.push('---');
    lines.push('');
  }

  // Action Items
  if (state.insights.actionItems.length > 0) {
    lines.push('## Action Items');
    lines.push('');
    for (const item of state.insights.actionItems) {
      const agent = AGENT_MAP[item.assignedTo];
      const checkmark = item.status === 'done' ? '[x]' : '[ ]';
      lines.push(`- ${checkmark} **${item.title}** — ${agent.name} (${item.priority} priority)`);
    }
    lines.push('');
    lines.push('---');
    lines.push('');
  }

  lines.push('*Generated by Orbit — Multi-Agent AI Workspace*');

  return lines.join('\n');
}

/**
 * Triggers a browser file download of the given text content.
 */
export function downloadFile(content: string, filename: string, mimeType = 'text/markdown') {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/**
 * Generates a safe filename from the workspace goal.
 */
export function generateFilename(goal: string): string {
  const slug = goal
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, '')
    .replace(/\s+/g, '-')
    .slice(0, 40);
  const date = new Date().toISOString().split('T')[0];
  return `orbit-${slug}-${date}.md`;
}
